create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  event_type text not null,
  path text not null,
  resource_unit integer,
  seconds_since_start integer,
  referrer text,
  ip_address inet,
  user_agent text,
  quiz_question_id text,
  quiz_question_prompt text,
  quiz_question_index integer,
  quiz_unit_label text,
  quiz_source_number integer,
  quiz_selected_answer text,
  quiz_correct_answer text,
  quiz_is_correct boolean,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz default now()
);

alter table analytics_events
  add column if not exists metadata jsonb not null default '{}'::jsonb,
  add column if not exists ip_address inet,
  add column if not exists quiz_question_id text,
  add column if not exists quiz_question_prompt text,
  add column if not exists quiz_question_index integer,
  add column if not exists quiz_unit_label text,
  add column if not exists quiz_source_number integer,
  add column if not exists quiz_selected_answer text,
  add column if not exists quiz_correct_answer text,
  add column if not exists quiz_is_correct boolean;

create index if not exists analytics_events_session_created_at_idx
  on analytics_events (session_id, created_at desc);

create index if not exists analytics_events_event_created_at_idx
  on analytics_events (event_type, created_at desc);

create index if not exists analytics_events_resource_unit_created_at_idx
  on analytics_events (resource_unit, created_at desc);

create index if not exists analytics_events_ip_address_created_at_idx
  on analytics_events (ip_address, created_at desc);

create index if not exists analytics_events_quiz_question_created_at_idx
  on analytics_events (quiz_question_id, created_at desc)
  where event_type = 'quiz_question_answered';

create index if not exists analytics_events_quiz_correct_created_at_idx
  on analytics_events (quiz_is_correct, created_at desc)
  where event_type = 'quiz_question_answered';

create index if not exists analytics_events_metadata_idx
  on analytics_events using gin (metadata);
